"""
training/generate_transactions.py
=================================

Generates transaction-level features for every user.

Input:
    training/data/users.csv           -- user-level features
    training/data/fraud_context.csv   -- per-user fraud ground truth
                                          written by generate_users.py

Output:
    training/data/transactions.csv

Appends 7 transaction features to every user. The same `FraudContext`
that shaped a user's voice/behavior/vehicle/history features is re-hydrated
here (by user_id) and threaded into the transaction and intent generators,
so a single fraud scenario's evidence is consistent across every subsystem
for that user rather than being re-rolled independently per stage.
"""

from pathlib import Path

import pandas as pd

from generators.transaction import generate_transaction
from generators.intent import generate_intent
from generators.fraud import FraudContext


# ==========================================================
# Configuration
# ==========================================================

INPUT = Path("training/data/users.csv")
FRAUD_INPUT = Path("training/data/fraud_context.csv")

OUTPUT = Path("training/data/transactions.csv")


# ==========================================================
# Transaction Generator
# ==========================================================

def generate_transaction_row(user: dict, fraud_context: FraudContext) -> dict:
    """
    Generate one transaction for a user, under their fraud context.
    """

    transaction = generate_transaction(fraud_context=fraud_context)

    intent = generate_intent(

        transaction["transaction_category"],
        fraud_context=fraud_context,

    )

    row = {

        **user,

        # Transaction (5)
        **transaction,

        # Intent (2)
        **intent,

    }

    return row


# ==========================================================
# Dataset Generation
# ==========================================================

def main():

    users = pd.read_csv(INPUT)

    if FRAUD_INPUT.exists():
        fraud_df = pd.read_csv(FRAUD_INPUT).set_index("user_id")
    else:
        # Fraud context is optional: if it's missing (e.g. users.csv was
        # generated by an older version of generate_users.py), every user
        # is treated as genuine rather than failing the whole run.
        fraud_df = None

    # NOTE: `DataFrame.iterrows()` yields each row as a `pd.Series`, which
    # forces every value in that row to a single common dtype (float64,
    # since the frame also has float columns). That silently corrupts every
    # integer column (user_id, kyc_verified, account_age_days, ...) into
    # floats. `to_dict("records")` preserves each column's original scalar
    # dtype per cell, so we use that instead.
    rows = []
    for user in users.to_dict("records"):
        if fraud_df is not None and user["user_id"] in fraud_df.index:
            fraud_context = FraudContext.from_row(
                fraud_df.loc[user["user_id"]]
            )
        else:
            fraud_context = FraudContext.genuine()

        rows.append(
            generate_transaction_row(user, fraud_context)
        )

    df = pd.DataFrame(rows)

    expected_columns = [

        # Metadata
        "user_id",

        # Identity
        "account_age_days",
        "kyc_verified",
        "phone_verified",
        "email_verified",
        "voice_enrolled",

        # Voice
        "speaker_similarity",
        "liveness_score",
        "audio_quality",
        "spoof_probability",

        # Behaviour
        "speech_rate_similarity",
        "pronunciation_similarity",
        "command_familiarity",
        "stress_score",
        "hesitation_score",

        # Vehicle
        "vehicle_speed",
        "engine_running",
        "location_familiarity",
        "time_familiarity",
        "driver_present",
        "seatbelt_fastened",

        # History
        "previous_trust_score",
        "failed_attempts",
        "successful_transactions",
        "fraud_history",

        # Transaction (5)
        "transaction_amount",
        "transaction_category",
        "beneficiary_type",
        "beneficiary_frequency",
        "transaction_risk",

        # Intent (2)
        "intent_type",
        "llm_confidence",

    ]

    if list(df.columns) != expected_columns:
        raise ValueError(
            f"Column mismatch.\nExpected:\n{expected_columns}\n\nGot:\n{list(df.columns)}"
        )

    OUTPUT.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    df.to_csv(
        OUTPUT,
        index=False,
    )

    print("=" * 60)
    print(f"Transactions Generated : {len(df):,}")
    print(f"Feature Columns        : {len(df.columns) - 1}")
    print(f"Saved To              : {OUTPUT}")
    print("=" * 60)


# ==========================================================
# Run
# ==========================================================

if __name__ == "__main__":
    main()
